from twilio.rest import Client

account_sid = 'ACe874b73af8a87e33a3eb4a3216f45929'  # Autogenerated by twilio
auth_token = ''  # Put your token authentication
client = Client(account_sid, auth_token)


def send_msg():
    message = client.messages.create(
        from_='whatsapp:+14155238886',  # Sandbox WhatsApp number
        body='Message sent from python project!',  # Message you want to send
        to='whatsapp:+'  # Put the mobile phone number where you want to receive the message
    )

    print(message.sid)
